-- drop table users if exists cascade;
create table users
(
    identity bigint generated by default as identity,
    id varchar(255),
    password varchar(255),
    name varchar(255),
    primary key (identity)
);
