-- drop table users if exists cascade;
create table users
(
    identity bigint generated by default as identity,
    id varchar(255),
    password varchar(255),
    name varchar(255),
    primary key (identity)
);
create table board
(
    articleId int generated by default as identity,
    writer varchar(255),
    title varchar(255),
    regDate date,
    updateDate date,
    boardCategory varchar(255),
    content varchar(255),
    likes int,
    primary key (articleId),foreign key (writer) references users
);
